import { processLocalDynamicQuery } from "../lib/ai/local-dynamic-tutor"

console.log("=================================================================")
console.log("TEST 1: Sentence 'She lives in Hanoi' + Label 'examples'")
console.log("=================================================================")
const res1 = processLocalDynamicQuery("She lives in Hanoi", [], "examples")
console.log(res1.reply)
console.log("Model:", res1.model)
console.log("Time:", res1.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 2: Sentence 'She lives in Hanoi' + Label 'grammar_lookup'")
console.log("=================================================================")
const res2 = processLocalDynamicQuery("She lives in Hanoi", [], "grammar_lookup")
console.log(res2.reply)
console.log("Model:", res2.model)
console.log("Time:", res2.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 3: Sentence 'She lives in Hanoi' + Label 'quiz'")
console.log("=================================================================")
const res3 = processLocalDynamicQuery("She lives in Hanoi", [], "quiz")
console.log(res3.reply)
console.log("Model:", res3.model)
console.log("Time:", res3.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 4: Sentence 'She don't like apple' + Label 'error_correction'")
console.log("=================================================================")
const res4 = processLocalDynamicQuery("She don't like apple", [], "error_correction")
console.log(res4.reply)
console.log("Model:", res4.model)
console.log("Time:", res4.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 5: Topic 'mạo từ' + Label 'examples'")
console.log("=================================================================")
const res5 = processLocalDynamicQuery("mạo từ", [], "examples")
console.log(res5.reply)
console.log("Model:", res5.model)
console.log("Time:", res5.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 6: Topic 'mạo từ' + Label 'grammar_lookup'")
console.log("=================================================================")
const res6 = processLocalDynamicQuery("mạo từ", [], "grammar_lookup")
console.log(res6.reply)
console.log("Model:", res6.model)
console.log("Time:", res6.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 7: Topic 'mạo từ' + Label 'error_correction'")
console.log("=================================================================")
const res7 = processLocalDynamicQuery("mạo từ", [], "error_correction")
console.log(res7.reply)
console.log("Model:", res7.model)
console.log("Time:", res7.executionTimeMs, "ms\n")

console.log("=================================================================")
console.log("TEST 8: Pair 'make vs do' + Label 'vocab_diff'")
console.log("=================================================================")
const res8 = processLocalDynamicQuery("make vs do", [], "vocab_diff")
console.log(res8.reply)
console.log("Model:", res8.model)
console.log("Time:", res8.executionTimeMs, "ms\n")
